# postgres/Dockerfile을 사용하여 커스텀 이미지를 빌드하고,
# init-db 폴더의 스크립트를 실행하여 데이터베이스를 초기화

services:
  db:
    # 공식 이미지 대신 프로젝트의 postgres 폴더에 있는 Dockerfile을 사용하여
    # pg_uuidv7이 설치된 커스텀 이미지를 빌드
    build: ./postgres

    container_name: band-matching-db
    ports:
      - "5432:5432"
    volumes:
      # 데이터베이스 데이터를 영구적으로 저장하기 위한 볼륨
      - postgres_data:/var/lib/postgresql/data
      # 컨테이너가 처음 생성될 때 실행될 초기화 스크립트 폴더를 연결
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=band-user
      - POSTGRES_PASSWORD=band-password
      - POSTGRES_DB=band-db
    restart: always

volumes:
  postgres_data:
