"""Update models based on frontend feedback

Revision ID: 4a61cd0f745c
Revises: 1cad6dda36bb
Create Date: 2025-08-20 07:18:24.842722

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a61cd0f745c"
down_revision: Union[str, Sequence[str], None] = "1cad6dda36bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_nickname"), table_name="users")
    op.create_index(op.f("ix_users_nickname"), "users", ["nickname"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_nickname"), table_name="users")
    op.create_index(op.f("ix_users_nickname"), "users", ["nickname"], unique=True)
    # ### end Alembic commands ###
