"""user error fix

Revision ID: 913d077c8061
Revises: 4a61cd0f745c
Create Date: 2025-08-21 08:40:20.301133

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "913d077c8061"
down_revision: Union[str, Sequence[str], None] = "4a61cd0f745c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
